
import type { ResearchPaper, Department, College, User } from '@/lib/types';

export const colleges: College[] = [
  { id: 'srmist-ramapuram', name: 'SRMIST Ramapuram', categories: ["Engineering and Technology", "Science and Humanities", "Management"] },
  { id: 'srm-trichy', name: 'SRM Trichy', categories: ["Engineering and Technology", "Science and Humanities", "Management"] },
  { id: 'easwari', name: 'Easwari College', categories: ["Engineering and Technology", "Science and Humanities", "Management"] },
  { id: 'srm-dental', name: 'SRM Dental College', categories: ["Dental"] },
];

export const departments: Department[] = [
  // Engineering and Technology
  { id: 'cse', name: 'CSE', collegeId: 'srmist-ramapuram', category: 'Engineering and Technology' },
  { id: 'mech', name: 'Mechanical', collegeId: 'srmist-ramapuram', category: 'Engineering and Technology' },
  { id: 'ece', name: 'ECE', collegeId: 'srmist-ramapuram', category: 'Engineering and Technology' },
  { id: 'eee', name: 'EEE', collegeId: 'srm-trichy', category: 'Engineering and Technology' },
  { id: 'aiml', name: 'AIML', collegeId: 'srm-trichy', category: 'Engineering and Technology' },
  { id: 'ds', name: 'Data Science', collegeId: 'easwari', category: 'Engineering and Technology' },
  { id: 'it', name: 'IT', collegeId: 'easwari', category: 'Engineering and Technology' },
  
  // Science and Humanities
  { id: 'comm', name: 'Commerce', collegeId: 'srmist-ramapuram', category: 'Science and Humanities' },
  { id: 'ca', name: 'Computer Application', collegeId: 'srmist-ramapuram', category: 'Science and Humanities' },
  { id: 'sh-cs', name: 'Computer Science', collegeId: 'srmist-ramapuram', category: 'Science and Humanities' },
  { id: 'sh-ds', name: 'Data Science', collegeId: 'srm-trichy', category: 'Science and Humanities' },
  { id: 'math', name: 'Maths', collegeId: 'srm-trichy', category: 'Science and Humanities' },
  { id: 'phy', name: 'Physics', collegeId: 'easwari', category: 'Science and Humanities' },
  { id: 'chem', name: 'Chemistry', collegeId: 'easwari', category: 'Science and Humanities' },

  // Management
  { id: 'bba', name: 'BBA', collegeId: 'srmist-ramapuram', category: 'Management' },
  { id: 'mba', name: 'MBA', collegeId: 'srm-trichy', category: 'Management' },
  
  // Dental
  { id: 'bds', name: 'BDS', collegeId: 'srm-dental', category: 'Dental' },
  { id: 'mds', name: 'MDS', collegeId: 'srm-dental', category: 'Dental' },
];

export const papers: ResearchPaper[] = [
  {
    id: '1',
    title: 'Advanced AI in Modern Computing',
    authors: [{ name: 'Dr. Ada Lovelace', isCorresponding: true }, { name: 'Dr. Charles Babbage', isCorresponding: false }],
    facultyId: 'F001',
    scopusId: 'S001',
    category: 'Engineering and Technology',
    department: 'CSE',
    college: 'SRMIST Ramapuram',
    publicationDate: '2023-05-10',
    journal: 'Journal of AI Research',
    volume: '42',
    doi: '10.1109/5.771073',
    type: 'journal',
    volumeName: 'Journal of AI Research',
    issue: '3',
    pageNo: '112-120',
    hasScopus: true,
    claimedBy: 'Dr. Ada Lovelace',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '2',
    title: 'Quantum Entanglement and its Applications',
    authors: [{ name: 'Dr. Albert Einstein', isCorresponding: true }, { name: 'Dr. Niels Bohr', isCorresponding: false }],
    facultyId: 'F002',
    scopusId: 'S002',
    category: 'Science and Humanities',
    department: 'Physics',
    college: 'SRMIST Ramapuram',
    publicationDate: '2023-01-15',
    journal: 'Physical Review Letters',
    volume: '130',
    doi: '10.1103/PhysRevLett.130.010501',
    type: 'journal',
    volumeName: 'Physical Review Letters',
    issue: '1',
    pageNo: '010501',
    hasScopus: true,
    claimedBy: 'Dr. Albert Einstein',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '3',
    title: 'Innovations in Bridge Construction Materials',
    authors: [{ name: 'Dr. John Roebling', isCorresponding: true }],
    facultyId: 'F003',
    scopusId: 'S003',
    category: 'Engineering and Technology',
    department: 'Mechanical',
    college: 'Easwari College',
    publicationDate: '2022-11-20',
    journal: 'ASCE Journal of Materials',
    volume: '34',
    doi: '10.1061/(ASCE)MT.1943-5533.000456',
    type: 'journal',
    volumeName: 'ASCE Journal of Materials in Civil Engineering',
    issue: '11',
    pageNo: '04022359',
    hasScopus: true,
    claimedBy: 'Dr. John Roebling',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '4',
    title: 'Next-Generation Wireless Communication Systems',
    authors: [{ name: 'Dr. Claude Shannon', isCorresponding: true }],
    facultyId: 'F004',
    scopusId: 'S004',
    category: 'Engineering and Technology',
    department: 'ECE',
    college: 'SRMIST Ramapuram',
    publicationDate: '2023-08-01',
    journal: 'IEEE Transactions on Communications',
    volume: '71',
    doi: '10.1109/TCOMM.2023.3245678',
    type: 'conference',
    volumeName: 'IEEE International Conference on Communications',
    issue: '8',
    pageNo: '5123-5128',
    hasScopus: true,
    claimedBy: 'Dr. Claude Shannon',
    authorNo: '1',
    isStudentScholar: true,
    studentScholars: [{ name: 'Student A', id: 'STU001' }],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '5',
    title: 'Organic Synthesis of Complex Molecules',
    authors: [{ name: 'Dr. Marie Curie', isCorresponding: true }],
    facultyId: 'F005',
    scopusId: 'S005',
    category: 'Science and Humanities',
    department: 'Chemistry',
    college: 'SRM Trichy',
    publicationDate: '2022-09-05',
    journal: 'Journal of Organic Chemistry',
    volume: '87',
    doi: '10.1021/acs.joc.2c01234',
    type: 'journal',
    volumeName: 'Journal of Organic Chemistry',
    issue: '18',
    pageNo: '12148-12159',
    hasScopus: false,
    claimedBy: 'Dr. Marie Curie',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '6',
    title: 'Thermodynamics of Jet Engines',
    authors: [{ name: 'Dr. Frank Whittle', isCorresponding: true }],
    facultyId: 'F006',
    scopusId: 'S006',
    category: 'Engineering and Technology',
    department: 'Mechanical',
    college: 'SRM Trichy',
    publicationDate: '2023-03-22',
    journal: 'Journal of Propulsion and Power',
    volume: '39',
    doi: '10.2514/1.B38642',
    type: 'book',
    volumeName: 'Basics of Jet Propulsion',
    issue: '2',
    pageNo: '1-300',
    hasScopus: true,
    claimedBy: 'Dr. Frank Whittle',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '7',
    title: 'Scalable Deep Learning for Big Data',
    authors: [{ name: 'Dr. Geoffrey Hinton', isCorresponding: false }, { name: 'Dr. Yann LeCun', isCorresponding: true }],
    facultyId: 'F007',
    scopusId: 'S007',
    category: 'Engineering and Technology',
    department: 'AIML',
    college: 'SRMIST Ramapuram',
    publicationDate: '2023-10-12',
    journal: 'Proceedings of NIPS',
    volume: 'N/A',
    doi: '10.1145/2969239.2969247',
    type: 'conference',
    volumeName: 'Advances in Neural Information Processing Systems',
    issue: '1',
    pageNo: '1-9',
    hasScopus: true,
    claimedBy: 'Dr. Yann LeCun',
    authorNo: '2',
    isStudentScholar: true,
    studentScholars: [{ name: 'Student B', id: 'STU002' }],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
   {
    id: '8',
    title: 'The Structure of Scientific Revolutions',
    authors: [{ name: 'Dr. Thomas Kuhn', isCorresponding: true }],
    facultyId: 'F008',
    scopusId: 'S008',
    category: 'Science and Humanities',
    department: 'Computer Application',
    college: 'SRM Trichy',
    publicationDate: '2021-06-12',
    journal: 'University of Chicago Press',
    volume: '4th Edition',
    doi: '10.7208/chicago/9780226458144.001.0001',
    type: 'book',
    volumeName: 'Scientific Revolutions',
    issue: '4',
    pageNo: '1-224',
    hasScopus: false,
    claimedBy: 'Dr. Thomas Kuhn',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '9',
    title: 'Microeconomic Theory',
    authors: [{ name: 'Dr. Andreu Mas-Colell', isCorresponding: true }],
    facultyId: 'F009',
    scopusId: 'S009',
    category: 'Management',
    department: 'BBA',
    college: 'SRMIST Ramapuram',
    publicationDate: '2022-04-18',
    journal: 'Oxford University Press',
    volume: 'N/A',
    doi: '10.1093/0195073401.001.0001',
    type: 'book',
    volumeName: 'Economics Series',
    issue: '1',
    pageNo: '1-1008',
    hasScopus: true,
    claimedBy: 'Dr. Andreu Mas-Colell',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '10',
    title: 'Principles of Neural Science',
    authors: [{ name: 'Dr. Eric Kandel', isCorresponding: true }],
    facultyId: 'F010',
    scopusId: 'S010',
    category: 'Science and Humanities',
    department: 'Maths',
    college: 'Easwari College',
    publicationDate: '2023-02-28',
    journal: 'McGraw-Hill',
    volume: '6th Edition',
    doi: '10.1036/0838577014',
    type: 'book',
    volumeName: 'Neuroscience Library',
    issue: '6',
    pageNo: '1-1760',
    hasScopus: true,
    claimedBy: 'Dr. Eric Kandel',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '11',
    title: 'Data Structures and Algorithms in Python',
    authors: [{ name: 'Dr. Michael Goodrich', isCorresponding: false }, { name: 'Dr. Roberto Tamassia', isCorresponding: true }],
    facultyId: 'F011',
    scopusId: 'S011',
    category: 'Engineering and Technology',
    department: 'IT',
    college: 'Easwari College',
    publicationDate: '2022-08-30',
    journal: 'Wiley',
    volume: '2nd Edition',
    doi: '10.1002/9781118671425',
    type: 'book',
    volumeName: 'Computer Science Series',
    issue: '2',
    pageNo: '1-768',
    hasScopus: true,
    claimedBy: 'Dr. Roberto Tamassia',
    authorNo: '2',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '12',
    title: 'Deep Learning with Python',
    authors: [{ name: 'François Chollet', isCorresponding: true }],
    facultyId: 'F012',
    scopusId: 'S012',
    category: 'Engineering and Technology',
    department: 'AIML',
    college: 'SRM Trichy',
    publicationDate: '2021-12-15',
    journal: 'Manning Publications',
    volume: '2nd Edition',
    doi: '10.1007/978-3-662-59535-5',
    type: 'book',
    volumeName: 'AI & Machine Learning',
    issue: '2',
    pageNo: '1-600',
    hasScopus: true,
    claimedBy: 'François Chollet',
    authorNo: '1',
    isStudentScholar: true,
    studentScholars: [{ name: 'François Chollet', id: 'STU003' }],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '13',
    title: 'Cognitive Psychology: A Student\'s Handbook',
    authors: [{ name: 'Michael Eysenck', isCorresponding: true }, { name: 'Mark Keane', isCorresponding: false }],
    facultyId: 'F013',
    scopusId: 'S013',
    category: 'Science and Humanities',
    department: 'Physics',
    college: 'SRMIST Ramapuram',
    publicationDate: '2020-05-19',
    journal: 'Routledge',
    volume: '8th Edition',
    doi: '10.4324/9780429446413',
    type: 'book',
    volumeName: 'Psychology Handbooks',
    issue: '8',
    pageNo: '1-752',
    hasScopus: false,
    claimedBy: 'Michael Eysenck',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '14',
    title: 'Marketing Management',
    authors: [{ name: 'Philip Kotler', isCorresponding: true }, { name: 'Kevin Lane Keller', isCorresponding: false }],
    facultyId: 'F014',
    scopusId: 'S014',
    category: 'Management',
    department: 'MBA',
    college: 'SRM Trichy',
    publicationDate: '2021-03-25',
    journal: 'Pearson',
    volume: '16th Edition',
    doi: '10.1108/S0743-9152(2012)0000029011',
    type: 'book',
    volumeName: 'Business & Management',
    issue: '16',
    pageNo: '1-888',
    hasScopus: true,
    claimedBy: 'Philip Kotler',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '15',
    title: 'Signal Processing for 6G Networks',
    authors: [{ name: 'Dr. Andrea Goldsmith', isCorresponding: true }],
    facultyId: 'F004',
    scopusId: 'S015',
    category: 'Engineering and Technology',
    department: 'ECE',
    college: 'SRMIST Ramapuram',
    publicationDate: '2024-01-05',
    journal: 'IEEE Wireless Communications',
    volume: '31',
    doi: '10.1109/MWC.001.2300134',
    type: 'conference',
    volumeName: 'IEEE Globecom',
    issue: '1',
    pageNo: '1-7',
    hasScopus: true,
    claimedBy: 'Dr. Andrea Goldsmith',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '16',
    title: 'Advances in Dental Implantology',
    authors: [{ name: 'Dr. Per-Ingvar Brånemark', isCorresponding: true }],
    facultyId: 'F016',
    scopusId: 'S016',
    category: 'Dental',
    department: 'MDS',
    college: 'SRM Dental College',
    publicationDate: '2023-06-15',
    journal: 'Journal of Clinical Periodontology',
    volume: '50',
    doi: '10.1111/jcpe.13780',
    type: 'journal',
    volumeName: 'Journal of Clinical Periodontology',
    issue: 'S25',
    pageNo: '5-15',
    hasScopus: true,
    claimedBy: 'Dr. Per-Ingvar Brånemark',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '17',
    title: 'Strategic Management in Technology Firms',
    authors: [{ name: 'Dr. Michael Porter', isCorresponding: true }],
    facultyId: 'F017',
    scopusId: 'S017',
    category: 'Management',
    department: 'MBA',
    college: 'Easwari College',
    publicationDate: '2022-08-20',
    journal: 'Harvard Business Review',
    volume: 'N/A',
    doi: '10.1225/R0801H',
    type: 'conference',
    volumeName: 'Strategic Management Society Conference',
    issue: '1',
    pageNo: '1-10',
    hasScopus: true,
    claimedBy: 'Dr. Michael Porter',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '18',
    title: 'Financial Modeling and Valuation',
    authors: [{ name: 'Dr. Aswath Damodaran', isCorresponding: true }],
    facultyId: 'F018',
    scopusId: 'S018',
    category: 'Management',
    department: 'BBA',
    college: 'Easwari College',
    publicationDate: '2023-04-11',
    journal: 'Wiley Finance',
    volume: '3rd Edition',
    doi: '10.1002/9781119727931',
    type: 'book',
    volumeName: 'Wiley Finance Series',
    issue: '3',
    pageNo: '1-960',
    hasScopus: true,
    claimedBy: 'Dr. Aswath Damodaran',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
   {
    id: '19',
    title: 'A Study on Marketing Strategies',
    authors: [{ name: 'Dr. Philip Kotler', isCorresponding: true }],
    facultyId: 'F019',
    scopusId: 'S019',
    category: 'Management',
    department: 'MBA',
    college: 'SRMIST Ramapuram',
    publicationDate: '2023-02-18',
    journal: 'Journal of Marketing',
    volume: '87',
    doi: '10.1177/00222429221123456',
    type: 'journal',
    volumeName: 'Journal of Marketing',
    issue: '2',
    pageNo: '155-171',
    hasScopus: true,
    claimedBy: 'Dr. Philip Kotler',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '20',
    title: 'Periodontal Disease Treatment',
    authors: [{ name: 'Dr. Jane Doe', isCorresponding: true }],
    facultyId: 'F020',
    scopusId: 'S020',
    category: 'Dental',
    department: 'BDS',
    college: 'SRM Dental College',
    publicationDate: '2023-11-30',
    journal: 'Journal of Dental Research',
    volume: '102',
    doi: '10.1177/00220345231187654',
    type: 'journal',
    volumeName: 'Journal of Dental Research',
    issue: '13',
    pageNo: '1447-1455',
    hasScopus: true,
    claimedBy: 'Dr. Jane Doe',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '21',
    title: 'Machine Learning for Drug Discovery',
    authors: [{ name: 'Dr. Daphne Koller', isCorresponding: true }],
    facultyId: 'F021',
    scopusId: 'S021',
    category: 'Science and Humanities',
    department: 'Data Science',
    college: 'SRM Trichy',
    publicationDate: '2024-02-28',
    journal: 'Nature Biotechnology',
    volume: '42',
    doi: '10.1038/s41587-024-02123-y',
    type: 'journal',
    volumeName: 'Nature Biotechnology',
    issue: '3',
    pageNo: '373-385',
    hasScopus: true,
    claimedBy: 'Dr. Daphne Koller',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '22',
    title: 'The Future of Robotics and Automation',
    authors: [{ name: 'Dr. Rodney Brooks', isCorresponding: true }],
    facultyId: 'F022',
    scopusId: 'S022',
    category: 'Engineering and Technology',
    department: 'EEE',
    college: 'Easwari College',
    publicationDate: '2021-07-19',
    journal: 'Robotics and Automation Magazine',
    volume: '28',
    doi: '10.1109/MRA.2021.3089765',
    type: 'journal',
    volumeName: 'IEEE Robotics and Automation Magazine',
    issue: '3',
    pageNo: '108-112',
    hasScopus: true,
    claimedBy: 'Dr. Rodney Brooks',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '23',
    title: 'Behavioral Economics and Public Policy',
    authors: [{ name: 'Dr. Richard Thaler', isCorresponding: false }, { name: 'Dr. Cass Sunstein', isCorresponding: true }],
    facultyId: 'F023',
    scopusId: 'S023',
    category: 'Management',
    department: 'BBA',
    college: 'SRMIST Ramapuram',
    publicationDate: '2022-05-01',
    journal: 'Journal of Economic Perspectives',
    volume: '36',
    doi: '10.1257/jep.36.2.1',
    type: 'conference',
    volumeName: 'AEA Annual Meeting',
    issue: '2',
    pageNo: '1-26',
    hasScopus: true,
    claimedBy: 'Dr. Cass Sunstein',
    authorNo: '2',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '24',
    title: 'Orthodontic Biomechanics: From Principle to Practice',
    authors: [{ name: 'Dr. Charles Burstone', isCorresponding: true }],
    facultyId: 'F024',
    scopusId: 'S024',
    category: 'Dental',
    department: 'MDS',
    college: 'SRM Dental College',
    publicationDate: '2021-12-10',
    journal: 'Quintessence Publishing',
    volume: 'Book',
    doi: '10.1007/978-3-662-43612-4',
    type: 'book',
    volumeName: 'Dental Science Library',
    issue: '1',
    pageNo: '1-400',
    hasScopus: true,
    claimedBy: 'Dr. Charles Burstone',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '25',
    title: 'Nanotechnology in Cancer Therapy',
    authors: [{ name: 'Dr. Robert Langer', isCorresponding: true }],
    facultyId: 'F025',
    scopusId: 'S025',
    category: 'Science and Humanities',
    department: 'Chemistry',
    college: 'SRMIST Ramapuram',
    publicationDate: '2024-03-15',
    journal: 'Science Translational Medicine',
    volume: '16',
    doi: '10.1126/scitranslmed.adi3456',
    type: 'journal',
    volumeName: 'Science Translational Medicine',
    issue: '739',
    pageNo: 'eadj3456',
    hasScopus: true,
    claimedBy: 'Dr. Robert Langer',
    authorNo: '1',
    isStudentScholar: true,
    studentScholars: [{ name: 'Student C', id: 'STU004' }],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '26',
    title: 'Sustainable Urban Development',
    authors: [{ name: 'Dr. Jane Jacobs', isCorresponding: true }],
    facultyId: 'F026',
    scopusId: 'S026',
    category: 'Engineering and Technology',
    department: 'IT',
    college: 'SRM Trichy',
    publicationDate: '2020-10-02',
    journal: 'Journal of the American Planning Association',
    volume: '86',
    doi: '10.1080/01944363.2020.1777401',
    type: 'journal',
    volumeName: 'Journal of the American Planning Association',
    issue: '4',
    pageNo: '424-437',
    hasScopus: false,
    claimedBy: 'Dr. Jane Jacobs',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '27',
    title: 'Cybersecurity for Critical Infrastructure',
    authors: [{ name: 'Dr. Eugene Spafford', isCorresponding: true }],
    facultyId: 'F027',
    scopusId: 'S027',
    category: 'Engineering and Technology',
    department: 'CSE',
    college: 'SRMIST Ramapuram',
    publicationDate: '2022-08-22',
    journal: 'IEEE Security & Privacy',
    volume: '20',
    doi: '10.1109/MSEC.2022.3168954',
    type: 'conference',
    volumeName: 'IEEE Symposium on Security and Privacy',
    issue: '4',
    pageNo: '24-31',
    hasScopus: true,
    claimedBy: 'Dr. Eugene Spafford',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '28',
    title: 'Marketing in the Age of Social Media',
    authors: [{ name: 'Dr. Gary Vaynerchuk', isCorresponding: true }],
    facultyId: 'F028',
    scopusId: 'S028',
    category: 'Management',
    department: 'MBA',
    college: 'Easwari College',
    publicationDate: '2023-09-18',
    journal: 'Journal of Interactive Marketing',
    volume: '56',
    doi: '10.1016/j.intmar.2023.06.002',
    type: 'journal',
    volumeName: 'Journal of Interactive Marketing',
    issue: '1',
    pageNo: '1-15',
    hasScopus: true,
    claimedBy: 'Dr. Gary Vaynerchuk',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '29',
    title: 'The Higgs Boson: Discovery and Implications',
    authors: [{ name: 'Dr. Peter Higgs', isCorresponding: true }],
    facultyId: 'F029',
    scopusId: 'S029',
    category: 'Science and Humanities',
    department: 'Physics',
    college: 'SRM Trichy',
    publicationDate: '2021-04-12',
    journal: 'Reviews of Modern Physics',
    volume: '93',
    doi: '10.1103/RevModPhys.93.025001',
    type: 'journal',
    volumeName: 'Reviews of Modern Physics',
    issue: '2',
    pageNo: '025001',
    hasScopus: true,
    claimedBy: 'Dr. Peter Higgs',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '30',
    title: 'Endodontic Microbiology',
    authors: [{ name: 'Dr. Dag Ørstavik', isCorresponding: true }],
    facultyId: 'F030',
    scopusId: 'S030',
    category: 'Dental',
    department: 'BDS',
    college: 'SRM Dental College',
    publicationDate: '2022-02-01',
    journal: 'Endodontic Topics',
    volume: '40',
    doi: '10.1111/et.12345',
    type: 'book',
    volumeName: 'Endodontic Topics',
    issue: '1',
    pageNo: '1-120',
    hasScopus: false,
    claimedBy: 'Dr. Dag Ørstavik',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '31',
    title: 'Advanced Materials for Aerospace Applications',
    authors: [{ name: 'Dr. Elon Musk', isCorresponding: true }],
    facultyId: 'F031',
    scopusId: 'S031',
    category: 'Engineering and Technology',
    department: 'Mechanical',
    college: 'Easwari College',
    publicationDate: '2024-05-20',
    journal: 'AIAA Journal',
    volume: '62',
    doi: '10.2514/1.J062890',
    type: 'journal',
    volumeName: 'AIAA Journal',
    issue: '5',
    pageNo: '2345-2356',
    hasScopus: true,
    claimedBy: 'Dr. Elon Musk',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '32',
    title: 'Differential Equations and Their Applications',
    authors: [{ name: 'Dr. Martin Braun', isCorresponding: true }],
    facultyId: 'F032',
    scopusId: 'S032',
    category: 'Science and Humanities',
    department: 'Maths',
    college: 'SRMIST Ramapuram',
    publicationDate: '2021-01-15',
    journal: 'Springer',
    volume: '4th Edition',
    doi: '10.1007/978-1-4612-4360-1',
    type: 'book',
    volumeName: 'Texts in Applied Mathematics',
    issue: '4',
    pageNo: '1-578',
    hasScopus: true,
    claimedBy: 'Dr. Martin Braun',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '33',
    title: 'The Principles of Computer Hardware',
    authors: [{ name: 'Dr. Alan Clements', isCorresponding: true }],
    facultyId: 'F033',
    scopusId: 'S033',
    category: 'Science and Humanities',
    department: 'Computer Science',
    college: 'SRM Trichy',
    publicationDate: '2020-05-20',
    journal: 'Oxford University Press',
    volume: '4th Edition',
    doi: '10.1093/acprof:oso/9780199641285.001.0001',
    type: 'book',
    volumeName: 'Computer Science Texts',
    issue: '4',
    pageNo: '1-800',
    hasScopus: false,
    claimedBy: 'Dr. Alan Clements',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '34',
    title: 'Impact of Big Data on Business Intelligence',
    authors: [{ name: 'Dr. Efraim Turban', isCorresponding: false }, { name: 'Dr. Ramesh Sharda', isCorresponding: true }],
    facultyId: 'F034',
    scopusId: 'S034',
    category: 'Engineering and Technology',
    department: 'Data Science',
    college: 'Easwari College',
    publicationDate: '2023-11-01',
    journal: 'Journal of Big Data',
    volume: '10',
    doi: '10.1186/s40537-023-00789-x',
    type: 'journal',
    volumeName: 'Journal of Big Data',
    issue: '1',
    pageNo: '111',
    hasScopus: true,
    claimedBy: 'Dr. Ramesh Sharda',
    authorNo: '2',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '35',
    title: 'Advanced Power Electronics',
    authors: [{ name: 'Dr. Muhammad Rashid', isCorresponding: true }],
    facultyId: 'F035',
    scopusId: 'S035',
    category: 'Engineering and Technology',
    department: 'EEE',
    college: 'SRM Trichy',
    publicationDate: '2024-01-20',
    journal: 'IEEE Transactions on Power Electronics',
    volume: '39',
    doi: '10.1109/TPEL.2023.3291234',
    type: 'journal',
    volumeName: 'IEEE Transactions on Power Electronics',
    issue: '1',
    pageNo: '1-14',
    hasScopus: true,
    claimedBy: 'Dr. Muhammad Rashid',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '36',
    title: 'Corporate Finance: Theory and Practice',
    authors: [{ name: 'Dr. Pierre Vernimmen', isCorresponding: true }],
    facultyId: 'F036',
    scopusId: 'S036',
    category: 'Management',
    department: 'MBA',
    college: 'SRM Trichy',
    publicationDate: '2022-06-10',
    journal: 'Wiley',
    volume: '5th Edition',
    doi: '10.1002/9781119561023',
    type: 'book',
    volumeName: 'Wiley Finance',
    issue: '5',
    pageNo: '1-1056',
    hasScopus: true,
    claimedBy: 'Dr. Pierre Vernimmen',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '37',
    title: 'Introduction to Algorithms',
    authors: [{ name: 'Thomas H. Cormen', isCorresponding: true }, { name: 'Charles E. Leiserson', isCorresponding: false }, { name: 'Ronald L. Rivest', isCorresponding: false }, { name: 'Clifford Stein', isCorresponding: false }],
    facultyId: 'F037',
    scopusId: 'S037',
    category: 'Engineering and Technology',
    department: 'CSE',
    college: 'SRM Trichy',
    publicationDate: '2022-07-01',
    journal: 'The MIT Press',
    volume: '4th Edition',
    doi: '10.7551/mitpress/14293.001.0001',
    type: 'book',
    volumeName: 'MIT Press Books',
    issue: '4',
    pageNo: '1-1312',
    hasScopus: true,
    claimedBy: 'Thomas H. Cormen',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '38',
    title: 'Solid State Physics',
    authors: [{ name: 'Neil W. Ashcroft', isCorresponding: false }, { name: 'N. David Mermin', isCorresponding: true }],
    facultyId: 'F038',
    scopusId: 'S038',
    category: 'Science and Humanities',
    department: 'Physics',
    college: 'Easwari College',
    publicationDate: '2023-03-05',
    journal: 'Cengage Learning',
    volume: '1st Edition',
    doi: '10.1017/CBO9780511813876',
    type: 'book',
    volumeName: 'Physics Library',
    issue: '1',
    pageNo: '1-848',
    hasScopus: false,
    claimedBy: 'N. David Mermin',
    authorNo: '2',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '39',
    title: 'Human-Computer Interaction',
    authors: [{ name: 'Alan Dix', isCorresponding: true }, { name: 'Janet Finlay', isCorresponding: false }, { name: 'Gregory Abowd', isCorresponding: false }, { name: 'Russell Beale', isCorresponding: false }],
    facultyId: 'F039',
    scopusId: 'S039',
    category: 'Science and Humanities',
    department: 'Computer Science',
    college: 'SRMIST Ramapuram',
    publicationDate: '2021-11-11',
    journal: 'Pearson',
    volume: '4th Edition',
    doi: '10.1145/572044.572046',
    type: 'book',
    volumeName: 'Computer Science Series',
    issue: '4',
    pageNo: '1-888',
    hasScopus: true,
    claimedBy: 'Alan Dix',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '40',
    title: 'Business Analytics: The Science of Data-Driven Decision Making',
    authors: [{ name: 'Dr. U. Dinesh Kumar', isCorresponding: true }],
    facultyId: 'F040',
    scopusId: 'S040',
    category: 'Science and Humanities',
    department: 'Data Science',
    college: 'SRMIST Ramapuram',
    publicationDate: '2024-04-02',
    journal: 'Wiley',
    volume: '2nd Edition',
    doi: '10.1002/9781119427966',
    type: 'book',
    volumeName: 'Wiley Business Analytics',
    issue: '2',
    pageNo: '1-512',
    hasScopus: true,
    claimedBy: 'Dr. U. Dinesh Kumar',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '41',
    title: 'Composite Materials in Dentistry',
    authors: [{ name: 'Dr. John Smith', isCorresponding: true }],
    facultyId: 'F041',
    scopusId: 'S041',
    category: 'Dental',
    department: 'BDS',
    college: 'SRM Dental College',
    publicationDate: '2022-10-15',
    journal: 'Dental Materials Journal',
    volume: '41',
    doi: '10.4012/dmj.2021-400',
    type: 'journal',
    volumeName: 'Dental Materials Journal',
    issue: '5',
    pageNo: 'e225-e232',
    hasScopus: true,
    claimedBy: 'Dr. John Smith',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '42',
    title: 'Maxillofacial Surgery Techniques',
    authors: [{ name: 'Dr. Emily White', isCorresponding: true }],
    facultyId: 'F042',
    scopusId: 'S042',
    category: 'Dental',
    department: 'MDS',
    college: 'SRM Dental College',
    publicationDate: '2023-01-20',
    journal: 'Journal of Oral and Maxillofacial Surgery',
    volume: '81',
    doi: '10.1016/j.joms.2022.09.010',
    type: 'journal',
    volumeName: 'Journal of Oral and Maxillofacial Surgery',
    issue: '1',
    pageNo: '100-108',
    hasScopus: true,
    claimedBy: 'Dr. Emily White',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '43',
    title: 'Pediatric Dentistry: A Clinical Approach',
    authors: [{ name: 'Dr. Sven Poulsen', isCorresponding: true }],
    facultyId: 'F043',
    scopusId: 'S043',
    category: 'Dental',
    department: 'BDS',
    college: 'SRM Dental College',
    publicationDate: '2022-05-25',
    journal: 'Wiley-Blackwell',
    volume: '3rd Edition',
    doi: '10.1002/9781118635847',
    type: 'book',
    volumeName: 'Clinical Dentistry Series',
    issue: '3',
    pageNo: '1-480',
    hasScopus: true,
    claimedBy: 'Dr. Sven Poulsen',
    authorNo: '1',
    isStudentScholar: true,
    studentScholars: [{ name: 'Student D', id: 'STU005' }],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  },
  {
    id: '44',
    title: 'Advanced Prosthodontics',
    authors: [{ name: 'Dr. Michael Brown', isCorresponding: true }],
    facultyId: 'F044',
    scopusId: 'S044',
    category: 'Dental',
    department: 'MDS',
    college: 'SRM Dental College',
    publicationDate: '2024-03-10',
    journal: 'Journal of Prosthetic Dentistry',
    volume: '129',
    doi: '10.1016/j.prosdent.2023.12.001',
    type: 'journal',
    volumeName: 'Journal of Prosthetic Dentistry',
    issue: '3',
    pageNo: '250-258',
    hasScopus: true,
    claimedBy: 'Dr. Michael Brown',
    authorNo: '1',
    isStudentScholar: false,
    studentScholars: [],
    q1: 'Q1 Data',
    q2: 'Q2 Data',
  }
];

export let users: User[] = [
  {
    id: '1',
    email: 'admin@scholarsync.com',
    role: 'admin',
    password: 'password',
  },
  {
    id: '2',
    email: 'ramapuram.eng@scholarsync.com',
    role: 'user',
    college: 'SRMIST Ramapuram',
    category: 'Engineering and Technology',
    password: 'password',
  },
  {
    id: '3',
    email: 'ramapuram.sh@scholarsync.com',
    role: 'user',
    college: 'SRMIST Ramapuram',
    category: 'Science and Humanities',
    password: 'password',
  },
  {
    id: '4',
    email: 'trichy.eng@scholarsync.com',
    role: 'user',
    college: 'SRM Trichy',
    category: 'Engineering and Technology',
    password: 'password',
  },
  {
    id: '5',
    email: 'easwari.mgmt@scholarsync.com',
    role: 'user',
    college: 'Easwari College',
    category: 'Management',
    password: 'password',
  },
  {
    id: '6',
    email: 'dental.user@scholarsync.com',
    role: 'user',
    college: 'SRM Dental College',
    category: 'Dental',
    password: 'password',
  },
  {
    id: '7',
    email: 'user@scholarsync.com',
    role: 'user',
    college: 'SRMIST Ramapuram',
    category: 'Management',
    password: 'password',
  }
];